import Link from "next/link";

export default function PrivacyPolicy() {
    return (<>
        <section className="py-10">
            <div className="max-w-7xl mx-auto w-full px-5 sm:px-10 md:px-12 lg:px-5">
                <div className="mx-auto text-center max-w-full mb-10">
                    <h1 className="relative font-semibold max-w-max mx-auto pb-2 font-display text-3xl sm:text-4xl md:text-5xl text-gray-800 after:absolute after:bottom-0 after:left-0 after:h-0.5 after:rounded-lg after:bg-gray-800 after:w-4">
                        Privacy Policy                    </h1>
                </div>
                <p class="text-sm text-primary font-bold">Last updated: December 27, 2024</p>
                <p class="mt-2 text-base text-gray-800">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <p class="mt-2 text-base text-gray-800">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

                <h2 class="mt-6 text-2xl font-semibold text-gray-900">Interpretation and Definitions</h2>

                <h3 class="mt-4 text-xl font-medium text-gray-800">Interpretation</h3>
                <p class="mt-2 text-base text-gray-800">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                <h3 class="mt-4 text-xl font-medium text-gray-800">Definitions</h3>
                <p class="mt-2 text-base text-gray-800">For the purposes of this Privacy Policy:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li><p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
                    <li><p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
                    <li><p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Shopify Extensions, Noida India.</p></li>
                    <li><p><strong>Cookies</strong> are small files placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
                    <li><p><strong>Country</strong> refers to: Delhi, India.</p></li>
                    <li><p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</p></li>
                    <li><p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p></li>
                    <li><p><strong>Service</strong> refers to the Website.</p></li>
                    <li><p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
                    <li><p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
                    <li><p><strong>Website</strong> refers to Shopify Extensions, accessible from <a href="https://www.shopify-extensions.com" target="_blank" class="text-orange-600 hover:underline">https://www.shopify-extensions.com</a></p></li>
                    <li><p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
                </ul>

                <h2 class="mt-6 text-2xl font-semibold text-gray-900">Collecting and Using Your Personal Data</h2>

                <h3 class="mt-4 text-xl font-medium text-gray-800">Types of Data Collected</h3>

                <h4 class="mt-4 text-lg font-semibold text-gray-900">Personal Data</h4>
                <p class="mt-2 text-base text-gray-800">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li><p>Email address</p></li>
                    <li><p>First name and last name</p></li>
                    <li><p>Phone number</p></li>
                    <li><p>Usage Data</p></li>
                </ul>

                <h4 class="mt-4 text-lg font-semibold text-gray-900">Usage Data</h4>
                <p class="mt-2 text-base text-gray-800">Usage Data is collected automatically when using the Service.</p>
                <p class="mt-2 text-base text-gray-800">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p class="mt-2 text-base text-gray-800">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>

                <h4 class="mt-4 text-lg font-semibold text-gray-900">Tracking Technologies and Cookies</h4>
                <p class="mt-2 text-base text-gray-800">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                    <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</li>
                </ul>
                <p class="mt-2 text-base text-gray-800">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                <p class="mt-2 text-base text-gray-800">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li><strong>Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
                    <li><strong>Cookies Policy / Notice Acceptance Cookies:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</li>
                    <li><strong>Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
                </ul>

                <h3 class="mt-6 text-xl font-medium text-gray-900">Use of Your Personal Data</h3>
                <p class="mt-2 text-base text-gray-800">The Company may use Personal Data for the following purposes:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                    <li><strong>For the performance of a contract:</strong> the development, compliance, and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                    <li><strong>To contact You:</strong> to send you updates and notifications via email, phone, SMS, or other methods.</li>
                    <li><strong>To provide You:</strong> with news, special offers, and information about other goods and services.</li>
                    <li><strong>For business transfers:</strong> if the Company undergoes a merger, acquisition, or asset sale.</li>
                </ul>

                <p class="mt-2 text-base text-gray-800">We may share Your personal information in the following situations:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li><strong>With Service Providers:</strong> to monitor and analyze the use of our Service.</li>
                    <li><strong>For business transfers:</strong> during negotiations or proceedings of any merger or acquisition.</li>
                    <li><strong>With Affiliates:</strong> with companies under the same ownership.</li>
                </ul>

                <h3 class="mt-6 text-xl font-medium text-gray-900">Retention of Your Personal Data</h3>
                <p class="mt-2 text-base text-gray-800">The Company will retain Your Personal Data only as long as necessary for the purposes set out in this Privacy Policy.</p>

                <h3 class="mt-6 text-xl font-medium text-gray-900">Transfer of Your Personal Data</h3>
                <p class="mt-2 text-base text-gray-800">Your Personal Data may be processed at locations outside of Your state, province, or country.</p>

                <h3 class="mt-6 text-xl font-medium text-gray-900">Delete Your Personal Data</h3>
                <p class="mt-2 text-base text-gray-800">You have the right to delete or request deletion of Your Personal Data.</p>

                <h3 class="mt-6 text-xl font-medium text-gray-900">Disclosure of Your Personal Data</h3>
                <p class="mt-2 text-base text-gray-800">The Company may disclose Your Personal Data under certain circumstances, such as business transactions or legal requirements.</p>

                <h3 class="mt-6 text-xl font-medium text-gray-900">Security of Your Personal Data</h3>
                <p class="mt-2 text-base text-gray-800">While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

                <h2 class="mt-6 text-2xl font-semibold text-gray-900">Children's Privacy</h2>
                <p class="mt-2 text-base text-gray-800">Our Service does not address anyone under the age of 13 and does not knowingly collect personal information from children.</p>

                <h2 class="mt-6 text-2xl font-semibold text-gray-900">Links to Other Websites</h2>
                <p class="mt-2 text-base text-gray-800">Our Service may contain links to other websites. We are not responsible for the privacy practices of other sites.</p>

                <h2 class="mt-6 text-2xl font-semibold text-gray-900">Changes to this Privacy Policy</h2>
                <p class="mt-2 text-base text-gray-800">We may update Our Privacy Policy from time to time. Changes will be posted on this page.</p>

                <h2 class="mt-6 text-2xl font-semibold text-gray-900">Contact Us</h2>
                <p class="mt-2 text-base text-gray-800">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul class="list-disc pl-5 mt-2 space-y-2 text-base text-gray-800">
                    <li>By email: <Link href="mailto:info@shopify-extensions.com" class="text-orange-600 hover:underline">info@shopify-extensions.com</Link></li>
                </ul>
            </div ></section></>)
}
